### PR TITLE
notebook for pixel cnn and vqvae

### PR DESCRIPTION
**Pull request by Drishttii**
@murphyk please review this.

### CODE REVIEW

**Comment by murphyk** [comment]
- generate_samples_from_priors_cpu is very slow, why can you not use a GPU?
- What is the difference between 'Codebook Sampling' (very slow) and 'Get samples' (fast)?

@Neoanarika @karalleyna  Any ideas?

**Comment by MLdoesML** [comment]
I think it is because we are using cpu. Hi @Drishttii, there should also shouldn't be a need to use gcp buckets to get the models you can just directly use wget. Also, I noticed you defined generate_samples_from_priors_cpu  you can directly just use the method from pixelcnn, unless u think defining the function is clearer.

**Comment by Drishttii** [comment]
Thank you for the comments. I am directly using `wget` now. And yes, `generate_samples_from_priors_cpu` this function was simply for clarity.

**Comment by Drishttii** [comment]
Removed the use of CPU. @Neoanarika could you please have a look at this.

**Comment by karalleyna** [comment]
LGTM. I reviewed the code and run it. It seems it is running on GPU hence fast :)

**Comment by MLdoesML** [comment]
Yup this works!

**Pull request merged**
