### PR TITLE
Create gaussian_hmm_with_normalizing_flows.ipynb

### PR DESCRIPTION
**Pull request by karalleyna**
# Description 

- 

```
python markov_flow_train.py --model gaussian --train_file /path/to/train --word_vec /path/to/word_vec_file
```

is equivalent to

```
train_file = "/content/struct_learning_with_flow/sample_data/ptb_tag_train_sub.txt"
word_vec = "/content/struct_learning_with_flow/sample_data/wsj_word_vec.pkl"
couple_layers = 4
args = init_config(train_file, word_vec, couple_layers=couple_layers, lr=5e-3)
main(args)
```

- 
```
python markov_flow_train.py \
        --model nice \
        --lr 0.01 \
        --train_file /path/to/train \
        --word_vec /path/to/word_vec_file \
        --load_gaussian /path/to/gaussian_model
```
is equivalent to

```
train_file = "/content/struct_learning_with_flow/sample_data/ptb_tag_train_sub.txt"
word_vec = "/content/struct_learning_with_flow/sample_data/wsj_word_vec.pkl"
couple_layers = 4
load_gaussian = f"/content/struct_learning_with_flow/dump_models/markov/pos_gaussian_{couple_layers}layers_0_0.pt"
model = "nice"
lr = 0.01
args = init_config(train_file, word_vec, lr=lr, model=model,  couple_layers=couple_layers, load_gaussian=load_gaussian)
main(args)
```

## Tags 

image

## Word Embeddings

image

### CODE REVIEW

**Comment by murphyk** [comment]
- what do you use faiss for?
- why do you specify faiss=1.6.5? According to 
https://github.com/facebookresearch/faiss/blob/master/INSTALL.md
you should be able to just use `conda install -c pytorch faiss-gpu` which will get whatever the latest version is.
Did you try that?

**Comment by karalleyna** [comment]
tsnecuda requires faiss, especially faiss=1.6.5. For example, if we run
```
!conda install -c pytorch faiss-gpu
!pip install -q tsnecuda==3.0.0+cu101 -f https://tsnecuda.isx.ai/tsnecuda_stable.html
```

we get the following error
```
ERROR: Could not find a version that satisfies the requirement faiss==1.6.5 (from tsnecuda)
ERROR: No matching distribution found for faiss==1.6.5
```

**Comment by murphyk** [comment]
I see. Maybe we should split this into 2 notebooks, the first trains the two HMM models (one with Gausssian emissions, and one with flows), and saves the learned embeddings. The second notebook will install faiss and visualize the data in 2d. The advantage of this is (1) we simplify the HMM code (no faiss, etc), and (2) the visualization code could be reused for other problems that want a fast version of tsne. (In fact you could demo it with random data as well, just to show the API). WDYT?

For the HMM code, it's odd that the Gaussian case prints lots of iterations and the flow case is silent. I suggest making both print output, but less than the Gaussian case. Also maybe you add some more comments explaining what you changed in the original HMM code.

**Comment by murphyk** [comment]
Actually, I've changed my mind - I don't think it's worth splitting into two, sicne I realized the viz code is quite specific to this use case (POS tags etc)

**Pull request merged**
