### PR TITLE
Converted `rnn_torch.ipynb` to `rnn_jax.ipynb`

### PR DESCRIPTION
**Pull request by codeboy5**
## Description

Converted `rnn_torch.ipynb` to `rnn_jax.ipynb`.

### Colab link

https://colab.research.google.com/github/codeboy5/probml-notebooks/blob/add-rnn-jax/rnn_jax.ipynb

### Issue 

[convert pytorch d2l.ai demos to JAX](https://github.com/probml/pyprobml/issues/686)

## Checklist:

- [x] Performed a self-review of the code
- [x] Tested on Google Colab.

## Potential problems/Important remarks

Trying to run the FLAX module version for 500 epochs, gives a out of memory error, so have done it for 250 epochs.

### CODE REVIEW

**Comment by UmarJ** [comment]
Hey @codeboy5!

I see you have used a lot of my code from #59. I was in the process of translating both `rnn_torch.ipynb` and `gru_torch.ipynb` as I said on the original issue, but I discovered that the Flax model is slower and has a much higher perplexity than both the vanilla JAX (which is equivalent to the PyTorch model in performance) and PyTorch models. It seems to plateau around 2.1 in the best case for me vs. 1.1 for JAX, even when keeping everything else constant.

I have ruled out randomness as the cause, because I've trained each network multiple times with different PRNG keys, but I always get the same result.

**Comment by codeboy5** [comment]
@UmarJ Yes I borrowed code from #59 as there is no point in reinventing the wheel. Yeah I also faced the issues the issues you mentioned, also I get out of memory error when I train for 500 epochs.

**Comment by gerdm** [comment]
Hi @codeboy5,

Looks good to me. However, if you are using somebody else's code and/or idea, it's imperative to cite them.

**Comment by codeboy5** [comment]
Hey @gerdm. 
I will update the notebook and cite the source.

**Comment by murphyk** [comment]
It seems that @UmarJ  has solved the problem in https://github.com/probml/probml-notebooks/pull/67.

**Pull request closed without merging**
