### PR TITLE
Translate Ensembles with Random Priors Demo to JAX 

### PR DESCRIPTION
**Pull request by petergchang**
## Description

Translated [Random Priors Demo](https://www.kaggle.com/code/gdmarmerola/introduction-to-randomized-prior-functions/notebook) from Keras to JAX/Flax.

Additionally implemented [beta-dependence of variance](https://raw.githubusercontent.com/peterchang0414/randomized_priors/main/uncertainty_betas.png) not present in the original notebook.

### Colab link
[Link to Colab Notebook](https://colab.research.google.com/github/peterchang0414/randomized_priors/blob/main/randomized_priors.ipynb)

### Issue 
[#708: translate ensembles with random priors demo from keras to JAX](https://github.com/probml/pyprobml/issues/708)

### Figures

[Gist for Figures](https://gist.github.com/peterchang0414/ad6319359d763653bece39561a126cf2)

## Checklist:

- [x] Performed a self-review of the code
- [x] Tested on Google Colab.

### CODE REVIEW

**Comment by petergchang** [comment]
I'd appreciate a code review, @murphyk @mjsML @gerdm 
Thanks!

**Comment by gerdm** [comment]
Looks great to me @peterchang0414! Very clean code and well commented.

**Comment by murphyk** [comment]
Thanks, @peterchang0414 , this looks great, I will merge. But then I plan to make a few small tweaks to your code (eg modify `get_predictions(X, params, beta)` so it actually uses `X` instead of hard-coding the global variable `x_grid` :)

**Comment by murphyk** [comment]
Hi @peterchang0414 . I checked in your code at  https://github.com/probml/probml-notebooks/blob/main/notebooks/randomized_priors.ipynb and made some tweaks. It would be great if you could speed up the code by using vmap over ensemble members. I like the plot with different betas. Can you also modify the final plot (comparing boostrap and/or prior) to show fill_between confidence intervals (and maybe with a larger beta to make things look more interesting)? Thanks!

PS. I added this example to the BNN chapter :)
Screen Shot 2022-04-04 at 1 59 50 PM

**Comment by petergchang** [comment]
Thank you very much @murphyk , I'm thrilled that the example is going in the book!

I made [another PR](https://github.com/probml/probml-notebooks/pull/69) to make the necessary adjustments.

I appreciate the thorough review!

**Pull request merged**
