### PR TITLE
Loads mix PPCA model ckpts from buckets and generates inference images

### PR DESCRIPTION
**Pull request by Drishttii**
@murphyk and @mjsML please review this. 

Model checkpoints are loaded from the probml-data bucket to generate inference images (3x3 and 10x10).

### CODE REVIEW

**Comment by Drishttii** [comment]
## Figures generated and saved:

a) Random samples:
samples_c_300_l_10_init_rnd_samples-3

b) Original masked samples (3X3):
original_samples_less-4

c) Reconstructed samples (3X3):
reconstructed_samples_less-4

d) Original masked samples (10X10):
original_samples-5

e) Reconstructed masked samples (10X10):
reconstructed_samples-5

f) Outliers:
outliers-3

**Comment by murphyk** [comment]
- Please factor out the huge blob of code in the 'MFA' and 'Utils' cells and store in pyprobml/scripts/mfa_celeba_helpers.py. Then you can type 
```
!wget -q https://raw.githubusercontent.com/probml/pyprobml/master/scripts/mfa_celeba_helpers.py
```
and use this in both your visualization/inference colab and training colab. This will make both colabs shorter, and avoid duplicating code (which can result in discrepenacies).
- Please add link/ref to https://github.com/eitanrich/gans-n-gmms
- When I run the 'inference' cell, it generates lots of figures, but does not display any of them! Please follow the example below to show images in the colab cells
```
from IPython.display import Image
fname = os.path.join(figures_dir, 'reconstructed_samples_less.jpg')
Image(fname)
```
- The 'inference' cell is the main point of this colab, but its a big unstructured blob that does too many things. Please break this into separate cells, one for generating samples, one for imputation (inpainting), one for outliers. Let the user control the size of the grid that is generated (either 3x3 or 10x10) for all 3 tasks, not just imputation. This way I can get small images for the book for all 3 tasks.
-

**Comment by murphyk** [comment]
Please refactor to use https://github.com/probml/pyprobml/blob/master/scripts/mfa_celeba_helpers.py

**Comment by murphyk** [comment]
Also only pip install needed packages

**Pull request merged**
