### PR TITLE
Added `conv2d_jax.ipynb` and `naive_bayes_mnist_jax.ipynb`

### PR DESCRIPTION
**Pull request by arpitvaghela**
## Description

Added `conv2d_jax.ipynb`  for `conv2d_torch.ipynb` and 
`naive_bayes_mnist_jax.ipynb` for `naive_bayes_mnist.ipynb`

### Colab link

https://github.com/arpitvaghela/probml-notebooks/blob/main/notebooks-d2l/conv2d_jax.ipynb

https://github.com/arpitvaghela/probml-notebooks/blob/main/notebooks-d2l/naive_bayes_mnist_jax.ipynb

### Issue 

https://github.com/probml/pyprobml/issues/686 

## Checklist:

- [x] Performed a self-review of the code
- [x] Tested on Google Colab.

### CODE REVIEW

**Comment by arpitvaghela** [comment]
@murphyk @mjsML @gerdm Requesting a review for this PR.

**Comment by murphyk** [comment]
For the conv2d_jax notebook, please update broken links to the  inline images ie. change to 

```
<img src="https://github.com/probml/probml-notebooks/blob/main/images/d2l-correlation.png?raw=true" height=200>


<img src="https://github.com/probml/probml-notebooks/blob/main/images/d2l-conv-multi-in.png?raw=true" height=200>

```

**Comment by murphyk** [comment]
For the naive Bayes colab, please replace `d2l.show_images` with code below (not tested...)

```
def show_images(imgs, num_rows, num_cols, titles=None, scale=1.5):
  # modified from https://raw.githubusercontent.com/d2l-ai/d2l-en/master/d2l/torch.py
    figsize = (num_cols * scale, num_rows * scale)
    _, axes = plt.subplots(num_rows, num_cols, figsize=figsize)
    axes = axes.flatten()
    for i, (ax, img) in enumerate(zip(axes, imgs)):
        try:
            img = np.array(img)
        except:
            pass
        ax.imshow(img)
        ax.axes.get_xaxis().set_visible(False)
        ax.axes.get_yaxis().set_visible(False)
        if titles:
            ax.set_title(titles[i])
    return axes
```

Finally remove
 ```
!wget https://raw.githubusercontent.com/d2l-ai/d2l-en/master/d2l/torch.py -q -O d2l.py
```

**Comment by murphyk** [comment]
Also, next time, please make one PR per notebook.

**Pull request merged**
